---
-   name: Copy docker-compose file to host
    copy:
        src: files/docker-compose
        dest: /home/{{ server_user }}/docker-compose.yml
        owner: "{{ server_user }}"
        group: "{{ server_user }}"
        mode: '0644'
-   name: Copy docker-compose template file
    template:
        src: templates/docker-compose
        dest: /home/{{ server_user }}/docker-compose.yml
        owner: "{{ server_user }}"
        group: "{{ server_user }}"
        mode: '0644'
-   name: Run docker-compose up to start MySql
    docker_compose:
        project_src: /home/{{ server_user }}/


-   name: Prepare exporter user
    shell: sudo docker exec {{ container_name }} mysql -u{{ MYSQL_USER }} -p{{ MYSQL_PASSWORD }} < files/dump.sql # -t? -i?

-   name: Pull prom/mysql-exporter
    shell: sudo docker pull prom/mysqld-exporter # sudo?

-   name: Run prom container
    shell: sudo docker run -d \
            -p {{ monitor_host_port }}:{{ monitor_container_port }} \
            --network host \
            -e DATA_SOURCE_NAME="exporter:{{ MYSQL_PASSWORD }}@(localhost:{{ host_port }})/" \
            --restart {{ policy }} \
            prom/{{ monitor_image_name }} \
            --collect.auto_increment.columns \
            --collect.info_schema.processlist \
            --collect.binlog_size \
            --collect.engine_innodb_status \
            --collect.engine_tokudb_status \
            --collect.global_status

# docker run -d \
#   -p 9104:9104 \
#   --network host \
#   -e DATA_SOURCE_NAME="exporter:pass@(localhost:3306)/" \
#   --restart always\
#   prom/mysqld-exporter:latest \
#   --collect.auto_increment.columns \
#   --collect.binlog_size \
#   --collect.engine_innodb_status \
#   --collect.engine_tokudb_status \
#   --collect.global_status