
tests:
skips:
- B303 # Ignore warnings about md5 hashing for gravatar picture by email
# - B404  # Ignore warnings about importing subprocess
# - B603  # Ignore warnings about calling subprocess.Popen without shell=True
# - B607  # Ignore warnings about calling subprocess.Popen without a full path to executable