version: 2
jobs:
  build:
    working_directory: ~/repo

    environment:
      FLASK_ENV: test
      FLASK_APP: microblog.py
    steps:
      - setup_remote_docker
      - run:
          name: run docker tests
          command: |
            make test