version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-node-browsers-legacy

    working_directory: ~/repo

    environment:
      FLASK_ENV: test
      FLASK_APP: microblog.py

    steps:
      # Step 1: optain repo from GitHub
      - checkout
      # Step 2: Create viritual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install-test
      # Step 3: run integration tests
      - run:
          name: run docker tests
          command: |
            make test
      # Step 4: run unittests
      # - run:
      #     name: run unittests
      #     command: |
      #       . venv/bin/activate
      #       make test-unit
      # # Step 4: run validations
      # - run:
      #     name: run validate
      #     command: |
      #       . venv/bin/activate
      #       make validate
      # - store_artifacts:
      #     path: tests/coverage_html