---

prometheus_version: 2.10.0

database_ip: "{{ groups['database'][0] }}"
database_port: "{{ 9104 }}"
litsen_database: "{{ database_ip }}:{{ database_port }}"

app_ip: "{{ groups['appServer'][0] }}"
app_port: "{{ 9104 }}"
litsen_app: "{{ app_ip }}:{{ app_port }}"

load_ip: "{{ groups['loadBalancer'][0] }}"
load_port: "{{ 9104 }}"
litsen_load: "{{ load_ip }}:{{ load_port }}"