FROM python:3.6-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

COPY . .
RUN python -m venv venv
RUN venv/bin/pip3 install -r requirements.txt


RUN chmod +x boot.sh

ENTRYPOINT ["./boot.sh"]