---
    -   hosts: database
        remote_user: mabn
        become: yes
        become_method: sudo
        vars:
          ansible_python_interpreter: /usr/bin/python3
        roles:
          - docker_dependencies
          - database