---
-   name: "Launch docker container with microblog application"
    docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        ports:
          - "{{ host_port }}:{{ container_port }}"
        restart_policy: "{{ policy }}"
        env:
          DATABASE_URL: "{{ database_url }}"